### PR TITLE
Smash gg

### PR DESCRIPTION
**Pull request by BrandonCookeDev**
PR to merge SmashGG branch into master.

### CODE REVIEW

**Comment by jessemtso** [comment]
currently failing some tests, specifically the rawData ones. not ready to be merged. @BrandonCookeDev look into failing test cases

**Comment by BrandonCookeDev** [comment]
Cases passed on my machine. But i'll look into it again

**Comment by jessemtso** [comment]
in vagrant?

**Comment by jessemtso** [comment]
this may help, its a (giant) output from one of the failed tests

[error.txt](https://github.com/yedi/garpr/files/314448/error.txt)

**Comment by BrandonCookeDev** [comment]
hmm so my local tests did pass before the PR but now they aren't. looking into it. Hope to be done by tonight

**Comment by jhertz** [comment]
Probably because i merged master into your branch (since master was updated since the base for ur PR)

**Comment by BrandonCookeDev** [comment]
it looks like SmashGG is still adding on to their API.
probably an agile methodology thing. I have screens 
left side is our test file I've included in our repository. Right side is a pull I just did on their api

pasted image at 2016_06_14 08_16 pm 1
pasted image at 2016_06_14 08_16 pm
pasted image at 2016_06_14 08_22 pm

there's a bunch of other examples
but basically it may be in our best interest to either refactor the get_raw tests to search for specific tags or to just ignore then until we can safely say they're done with updates?

**Comment by jessemtso** [comment]
perhaps write some tests to ensure that tag extraction and match extraction works regardless, and you can comment out hte ‘test raw data’ test for now (and we’ll make a TODO to re-enable them when the API is fully stable)

**Comment by BrandonCookeDev** [comment]
Substitute tests added, 
One of them has an issue where a Winners ID randomly comes up None. It is probably just the supposed api updates. I skip this test for now. The other one uses a known url for testing. This test passes. 

We need to revisit after these after the supposed API Updates blow over. I think an issue ticket should be open for testing in a week or two from now.

**Comment by jessemtso** [comment]
unit tests that are due to API instability are skipped. merging into master

**Pull request merged**
