### PR TITLE
Add local DB to vagrant for testing

### PR DESCRIPTION
**Pull request by jschnei**
Initializing vagrant now also initializes a local DB with data for testing (restoring it from the dump yedi/jesse provided [here](https://github.com/yedi/garpr/files/299034/garpr-db.zip)). Should resolve [#17](https://github.com/yedi/garpr/issues/17).

There should be one admin user with un: "devuser" and pw: "devpass01". Authentication stuff is stored in the 'admin' db; the rest should be stored in the 'garpr' db. 

(Also, changed the hostname in script.js to reflect the vagrant private IP.)

### CODE REVIEW

**Comment by jessemtso** [comment]
@jschnei is this ready to be merged?

**Comment by jschnei** [comment]
@jessemtso 

Should be ready to be merged, but maybe someone else should test it out first.

There were actually two copies of passlib in requirements.txt for some reason, and it was causing some errors with pip.

**Comment by jessemtso** [comment]
rodger that, testing

**Comment by jessemtso** [comment]
FAILED (errors=5, failures=6)

not ready yet. will look into it

**Comment by jschnei** [comment]
Ah, didn't realize we had nosetests. Should have checked those.

It looks like a lot of the tests assume that 'norcal' is a region, but in the data we have there is no one from 'norcal'; I expect this is the main reason behind most of the failures (also we changed the default region from 'norcal' to 'newjersey' somewhere in server.py). I'll take a closer look tomorrow.

**Comment by jessemtso** [comment]
yeah, we setup fake dao's for testing in the test harness:
https://github.com/yedi/garpr/blob/master/test/test_server.py#L40

but that's breaking w/ the current def region. something test-suitey should be done. im shleepy

**Comment by jschnei** [comment]
So, the above commit should fix the tests that were failing. Here's a summary of the issues that came up:

1. Initializing the DAO object used to require specifying a region, even for region-independent things (like managing sessions). Using the default region led to an error when it was changed from "norcal" to "newjersey", since "newjersey" is not a valid region for the test data. I changed it so that you can now either pass a valid region or None to the DAO constructor. 

2. At some point in the past, the criteria for whether a player is inactive or not seem to have changed (seemingly from requiring 1 tournament in x days to 2 tournaments in 60 days). This caused some errors in some of the ranking tests. You can now pass in the day limit and tournament number to rankings.generate_rankings. 

3. The logic for managing pending merges in server.py seemed incomplete. It should work now (hopefully). 

4. Some code that disallowed tournaments with an empty 'raw' field was commented out. I uncommented it (but if for some reason we want to allow those tournaments, we should change the tests).

**Comment by jessemtso** [comment]
passing all tests, lgtm.

squash and merge!

**Pull request closed without merging**
